services:
  app:
    build:
      context: .
    image: vite-dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    # volumes:
    #   - .:/app
    # command: npm run dev
    # command: tail -f /dev/null
# docker exec -it <docker_name> bash
# tao may ao A de build image vite-dev
# docker run vite-dev -e VITE_GRAPHQL_SERVER=http://localhost:4000 -e .....